name: Publish package to GitHub Packages
on:
  push:

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eric2788/maven-jar-publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
